session_name: services
start_directory: '~'
windows:
    - window_name: services
      focus: True
      layout: main-horizontal
      start_directory: ~/dev/services
      shell_command_before:
          - cd .
      panes:
          - focus: True
            shell_command:
                - tmux resize-pane -Z
                - venv
                - v
          - shell_command:
                - venv
                - cl
